### ISSUE TITLE
the version of the SUMO

### ISSUE THREAD

**Issue by wenliyuan** [Ring367/A-Deep-Reinforcement-Learning-Network-for-Traffic-Light-Cycle-Control#2]
I try the code under the environment of ubuntu16.04  sumo-0.32.0, but there are some errors about traci. May I ask you about the version of your sumo?

**Comment by chAngeZhaoZhanBo** [comment]
I used sumo-1.2.0 on windows to try the code and at first I got some errors about traci too.
For example, the "p = traci.vehicle.getSubscriptionResults()" should be
 " p = traci.vehicle.getSubscriptionResults(veh_id)"
If you still have some problems, please communicate with me, my email is 572295110zhao@gmail.com
and I can discuss the code with you

**Comment by chAngeZhaoZhanBo** [comment]
> I try the code under the environment of ubuntu16.04 sumo-0.32.0, but there are some errors about traci. May I ask you about the version of your sumo?

I used sumo-1.2.0 on windows to try the code and at first I got some errors about traci too.
For example, the "p = traci.vehicle.getSubscriptionResults()" should be
" p = traci.vehicle.getSubscriptionResults(veh_id)"
If you still have some problems, please communicate with me, my email is 572295110zhao@gmail.com
and I can discuss the code with you

**Comment by wenliyuan** [comment]
Thanks a lot.

**Comment by way-thu** [comment]
@wenliyuan @chAngeZhaoZhanBo hello, have you successfully run this project? i meet some issues, hope have a chance to communicate with you
